apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: flights-api-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: flights-api  
    spec:     # pod spec                  
      containers: 
      - name: flights-api 
        image: gcr.io/mariadb-technical-marketing/flights-api-image:v2 # image we pushed
        ports:
        - containerPort: 80